# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a684a26686cfe53810ca5c5b86d2afdf5f0c144ce806db62e80749f040b3d21b972dcb11116ff85bea71750c797ff00e4d75e8123f9e0eb45c07dbb717278d02

test:
  secret_key_base: 3000a20c226f587c576769d331090214bb2a8481380c5153de0e3662ff846a7ad3363d033df6ba2d1076925d1ef02836468cbce77eb90b818d46d24ae8fca934

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
